# Project specific config

#http://lint.travis-ci.org/

os:
    - linux

dist: bionic

addons:
    apt:
        packages:
        - build-essential
        - git
        - libgnome-keyring-dev
        - fakeroot

language:
    - python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
  - python3 -m pip install -U mypy
  - python3 -m pip install -U typed-ast
  - python3 -m pip install -U requests

branches:
  only:
    - master

git:
  depth: 10

env:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta

script: './BUILDME'

notifications:
  email:
    on_success: never
    on_failure: change
